version: '3.5'

services:
  etcd:
    container_name: builder-etcd
    image: bitnami/etcd:3.5.2
    ports:
      - 2379:2379
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_AUTO_COMPACTION_MODE: "revision"
      ETCD_AUTO_COMPACTION_RETENTION: 1002
      ETCD_QUOTA_BACKEND_BYTES: 4294967296

networks:
  default:
    name: builder_dev
