version: '3.5'

services:
  mysql:
    container_name: builder-mysql
    image: mysql:5.7.36
    environment:
      MYSQL_DATABASE: "admin123"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - 3306:3306
    volumes:
        - ${DOCKER_ROOT_DIR:-.}/volumes/mysql/data:/var/lib/mysql

networks:
  default:
    name: builder_dev
