version: '3.5'

services:
  rabbitmq1:
    container_name: builder-rabbitmq1
    image: rabbitmq:3.8.5-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ${DOCKER_ROOT_DIR:-.}/volumes/rabbitmq/data1:/var/lib/rabbitmq

  rabbitmq2:
    container_name: builder-rabbitmq2
    image: rabbitmq:3.8.5-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ${DOCKER_ROOT_DIR:-.}/volumes/rabbitmq/data2:/var/lib/rabbitmq
    depends_on:
      - rabbitmq1

  rabbitmq3:
    container_name: builder-rabbitmq3
    image: rabbitmq:3.8.5-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ${DOCKER_ROOT_DIR:-.}/volumes/rabbitmq/data3:/var/lib/rabbitmq
    depends_on:
      - rabbitmq1

  haproxy:
    container_name: builder-haproxy
    image: haproxy:1.7
    ports:
      - 15671:15672
      - 5671:5672
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3

networks:
  default:
    name: builder_dev
